[package]
name = "weather"
version = "0.1.0"
authors = ["Carter Himmel <me@fyko.net>"]
edition = "2018"

[dependencies]
clap = {version = "~2", features = ["yaml"]}
reqwest = "0.10"
tokio = { version = "0.2", features = ["full"] }